export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const VERIFICATION_SUCCESS = 'VERIFICATION_SUCCESS';
export const VERIFICATION_FAIL = 'VERIFICATION_FAIL';
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const GET_PORTFOLIO = 'GET_PORTFOLIO'
export const PORTFOLIO_ERROR= 'PORTFOLIO_ERROR'
export const GET_STOCK= 'GET_STOCK'
export const STOCK_ERROR= 'STOCK_ERROR'
export const BUY_STOCK= 'BUY_STOCK'
export const BUY_ERROR= 'BUY_ERROR'
export const SELL_ERROR= 'SELL_ERROR'
export const GET_NEWS= 'GET_NEWS'
export const NEWS_ERROR= 'NEWS_ERROR'
export const ADD_NEWS= 'ADD_NEWS'
export const CLEAR_PROFILE= 'CLEAR_PROFILE'
export const END_ERROR= 'END_ERROR'
export const ROUND_END= 'ROUND_END'